<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $breadCategory = Category::where('slug', 'bread-bakery')->first()->id;
        $cakeCategory = Category::where('slug', 'cake-pastry')->first()->id;
        $savouryCategory = Category::where('slug', 'savoury')->first()->id;
        $sweetsCategory = Category::where('slug', 'sweets')->first()->id;
        $ramadanCategory = Category::where('slug', 'ramadan-menu')->first()->id;
        $corporateCategory = Category::where('slug', 'corporate-orders')->first()->id;

        $products = [
            // Bread & Bakery
            [
                'category_id' => $breadCategory,
                'name' => 'Butter Bun',
                'slug' => 'butter-bun',
                'sku' => 'LVD-BB-001',
                'short_description' => 'Soft and fluffy butter buns, baked fresh every morning.',
                'description' => 'Our Butter Buns are made with premium quality flour, fresh butter, and a touch of sweetness. Perfect for breakfast or an afternoon snack. Soft, pillowy, and utterly delicious.',
                'ingredients' => 'Flour, Butter, Sugar, Yeast, Salt, Milk, Eggs',
                'price' => 35.00,
                'discount_price' => null,
                'weight' => '80g',
                'stock' => 50,
                'is_featured' => true,
                'tags' => ['bread', 'butter', 'breakfast', 'fresh'],
            ],
            [
                'category_id' => $breadCategory,
                'name' => 'Milk Bread Loaf',
                'slug' => 'milk-bread-loaf',
                'sku' => 'LVD-MB-001',
                'short_description' => 'Pillowy soft milk bread loaf, perfect for sandwiches and toast.',
                'description' => 'Our Milk Bread Loaf is made with the finest milk, flour, and butter. The result is an incredibly soft, slightly sweet bread perfect for sandwiches, French toast, or just enjoying with butter.',
                'ingredients' => 'Flour, Full Cream Milk, Butter, Sugar, Yeast, Salt, Eggs',
                'price' => 120.00,
                'discount_price' => 99.00,
                'weight' => '400g',
                'stock' => 30,
                'is_featured' => true,
                'tags' => ['bread', 'milk', 'loaf', 'sandwich'],
            ],
            [
                'category_id' => $breadCategory,
                'name' => 'Garlic Bread',
                'slug' => 'garlic-bread',
                'sku' => 'LVD-GB-001',
                'short_description' => 'Crispy garlic bread with herb butter, perfect with any meal.',
                'description' => 'Our Garlic Bread is loaded with fresh garlic, herb butter, and baked to golden perfection. A crowd favorite that pairs perfectly with soups, pasta, or as a standalone snack.',
                'ingredients' => 'Baguette, Butter, Fresh Garlic, Parsley, Salt',
                'price' => 80.00,
                'discount_price' => null,
                'weight' => '200g',
                'stock' => 40,
                'is_featured' => false,
                'tags' => ['bread', 'garlic', 'savory', 'herb'],
            ],

            // Cake & Pastry
            [
                'category_id' => $cakeCategory,
                'name' => 'Chocolate Éclair',
                'slug' => 'chocolate-eclair',
                'sku' => 'LVD-CE-001',
                'short_description' => 'Classic French chocolate éclairs with rich custard filling.',
                'description' => 'Delicate choux pastry filled with velvety vanilla custard cream and topped with a smooth chocolate glaze. Our Chocolate Éclairs are a true pastry masterpiece.',
                'ingredients' => 'Choux Pastry (Flour, Butter, Eggs), Custard Cream (Milk, Sugar, Eggs, Vanilla), Chocolate Glaze',
                'price' => 60.00,
                'discount_price' => null,
                'weight' => '80g',
                'stock' => 25,
                'is_featured' => true,
                'tags' => ['pastry', 'chocolate', 'french', 'custard'],
            ],
            [
                'category_id' => $cakeCategory,
                'name' => 'Chocolate Cake',
                'slug' => 'chocolate-cake',
                'sku' => 'LVD-CC-001',
                'short_description' => 'Rich, moist chocolate cake with ganache frosting. Perfect for celebrations.',
                'description' => 'Our signature Chocolate Cake is the ultimate indulgence. Made with premium cocoa, rich butter, and finished with a silky chocolate ganache. Perfect for birthdays, celebrations, or any special moment.',
                'ingredients' => 'Flour, Premium Cocoa, Butter, Sugar, Eggs, Milk, Vanilla, Baking Powder',
                'price' => 850.00,
                'discount_price' => 750.00,
                'weight' => '1kg',
                'stock' => 15,
                'is_featured' => true,
                'tags' => ['cake', 'chocolate', 'birthday', 'celebration'],
            ],
            [
                'category_id' => $cakeCategory,
                'name' => 'Vanilla Cake',
                'slug' => 'vanilla-cake',
                'sku' => 'LVD-VC-001',
                'short_description' => 'Classic vanilla sponge cake with buttercream frosting.',
                'description' => 'Light, fluffy vanilla sponge layered with smooth vanilla buttercream. This timeless classic is perfect for any occasion and can be customized with your choice of decoration.',
                'ingredients' => 'Flour, Butter, Sugar, Eggs, Vanilla Extract, Milk, Baking Powder, Buttercream',
                'price' => 750.00,
                'discount_price' => null,
                'weight' => '1kg',
                'stock' => 20,
                'is_featured' => false,
                'tags' => ['cake', 'vanilla', 'classic', 'birthday'],
            ],
            [
                'category_id' => $cakeCategory,
                'name' => 'Red Velvet Cake',
                'slug' => 'red-velvet-cake',
                'sku' => 'LVD-RVC-001',
                'short_description' => 'Stunning red velvet cake with cream cheese frosting.',
                'description' => 'Our Red Velvet Cake is a showstopper. Rich velvety red sponge layers filled and frosted with tangy cream cheese frosting. A luxurious cake that tastes as good as it looks.',
                'ingredients' => 'Flour, Butter, Sugar, Eggs, Cocoa, Red Food Coloring, Buttermilk, Cream Cheese Frosting',
                'price' => 950.00,
                'discount_price' => 850.00,
                'weight' => '1kg',
                'stock' => 10,
                'is_featured' => true,
                'tags' => ['cake', 'red velvet', 'cream cheese', 'premium'],
            ],
            [
                'category_id' => $cakeCategory,
                'name' => 'Black Forest Cake',
                'slug' => 'black-forest-cake',
                'sku' => 'LVD-BFC-001',
                'short_description' => 'Classic Black Forest cake with cherries and whipped cream.',
                'description' => 'Layers of rich chocolate sponge, whipped cream, and cherries make our Black Forest Cake an absolute delight. A timeless German classic made with the finest ingredients.',
                'ingredients' => 'Chocolate Sponge, Whipped Cream, Cherries, Chocolate Shavings, Kirsch Syrup',
                'price' => 1050.00,
                'discount_price' => null,
                'weight' => '1kg',
                'stock' => 8,
                'is_featured' => true,
                'tags' => ['cake', 'black forest', 'cherry', 'premium'],
            ],
            [
                'category_id' => $cakeCategory,
                'name' => 'Cashewnut Tart',
                'slug' => 'cashewnut-tart',
                'sku' => 'LVD-CNT-001',
                'short_description' => 'Buttery pastry tarts filled with caramelized cashew nuts.',
                'description' => 'Our Cashewnut Tarts feature a buttery, crispy pastry shell filled with a rich caramelized cashew nut filling. A perfect balance of crunchy and sweet.',
                'ingredients' => 'Pastry Shell (Flour, Butter, Sugar), Cashew Nuts, Caramel, Cream',
                'price' => 55.00,
                'discount_price' => null,
                'weight' => '60g',
                'stock' => 30,
                'is_featured' => false,
                'tags' => ['pastry', 'tart', 'cashew', 'nuts'],
            ],
            [
                'category_id' => $cakeCategory,
                'name' => 'Cream Pastry',
                'slug' => 'cream-pastry',
                'sku' => 'LVD-CP-001',
                'short_description' => 'Light and airy cream pastry with fresh whipped cream.',
                'description' => 'Delicate puff pastry layers filled with fresh whipped cream and dusted with powdered sugar. Light, airy, and irresistibly delicious.',
                'ingredients' => 'Puff Pastry, Fresh Cream, Powdered Sugar, Vanilla',
                'price' => 65.00,
                'discount_price' => null,
                'weight' => '90g',
                'stock' => 20,
                'is_featured' => false,
                'tags' => ['pastry', 'cream', 'puff', 'light'],
            ],
            [
                'category_id' => $cakeCategory,
                'name' => 'Fruit Pastry',
                'slug' => 'fruit-pastry',
                'sku' => 'LVD-FP-001',
                'short_description' => 'Fresh fruit pastry with seasonal fruits and cream.',
                'description' => 'A beautiful pastry tart filled with fresh cream and topped with an assortment of seasonal fresh fruits. A refreshing and elegant treat.',
                'ingredients' => 'Pastry Shell, Cream Patissiere, Seasonal Fresh Fruits, Apricot Glaze',
                'price' => 75.00,
                'discount_price' => 65.00,
                'weight' => '100g',
                'stock' => 15,
                'is_featured' => false,
                'tags' => ['pastry', 'fruit', 'fresh', 'seasonal'],
            ],

            // Savoury
            [
                'category_id' => $savouryCategory,
                'name' => 'Chicken Patties',
                'slug' => 'chicken-patties',
                'sku' => 'LVD-ChP-001',
                'short_description' => 'Flaky pastry pockets filled with spiced chicken filling.',
                'description' => 'Our Chicken Patties feature a golden, flaky pastry shell filled with a perfectly spiced chicken mixture. A classic Bangladeshi bakery snack that never disappoints.',
                'ingredients' => 'Puff Pastry, Chicken, Onion, Ginger, Garlic, Green Chili, Spices',
                'price' => 45.00,
                'discount_price' => null,
                'weight' => '100g',
                'stock' => 60,
                'is_featured' => true,
                'tags' => ['savoury', 'chicken', 'pastry', 'snack'],
            ],
            [
                'category_id' => $savouryCategory,
                'name' => 'Chicken Roll',
                'slug' => 'chicken-roll',
                'sku' => 'LVD-CR-001',
                'short_description' => 'Soft paratha wrapped with spicy grilled chicken filling.',
                'description' => 'Our signature Chicken Roll features tender, marinated grilled chicken wrapped in a soft, flaky paratha with fresh salad, chili sauce, and special seasoning. A complete meal in every bite.',
                'ingredients' => 'Paratha, Grilled Chicken, Salad, Onion, Chili Sauce, Special Seasoning',
                'price' => 85.00,
                'discount_price' => null,
                'weight' => '200g',
                'stock' => 40,
                'is_featured' => true,
                'tags' => ['savoury', 'chicken', 'roll', 'lunch'],
            ],
            [
                'category_id' => $savouryCategory,
                'name' => 'Beef Puff',
                'slug' => 'beef-puff',
                'sku' => 'LVD-BP-001',
                'short_description' => 'Crispy puff pastry with spiced minced beef filling.',
                'description' => 'Golden, crispy puff pastry filled with a perfectly seasoned minced beef mixture. Our Beef Puffs are a popular choice for snacks, tea time, and light meals.',
                'ingredients' => 'Puff Pastry, Minced Beef, Onion, Ginger, Garlic, Mixed Spices',
                'price' => 50.00,
                'discount_price' => null,
                'weight' => '110g',
                'stock' => 50,
                'is_featured' => false,
                'tags' => ['savoury', 'beef', 'puff', 'snack'],
            ],
            [
                'category_id' => $savouryCategory,
                'name' => 'Egg Fried Rice with Chicken',
                'slug' => 'egg-fried-rice-chicken',
                'sku' => 'LVD-EFRC-001',
                'short_description' => 'Flavourful egg fried rice served with tender chicken pieces.',
                'description' => 'Our Egg Fried Rice with Chicken is a satisfying meal that combines perfectly wok-tossed fried rice with tender marinated chicken pieces, fresh vegetables, and aromatic spices.',
                'ingredients' => 'Basmati Rice, Eggs, Chicken, Bell Peppers, Carrots, Spring Onion, Soy Sauce, Spices',
                'price' => 150.00,
                'discount_price' => 130.00,
                'weight' => '350g',
                'stock' => 30,
                'is_featured' => false,
                'tags' => ['rice', 'chicken', 'lunch', 'meal'],
            ],
            [
                'category_id' => $savouryCategory,
                'name' => 'Egg Fried Rice with Beef',
                'slug' => 'egg-fried-rice-beef',
                'sku' => 'LVD-EFRB-001',
                'short_description' => 'Aromatic egg fried rice served with succulent beef pieces.',
                'description' => 'Rich and flavorful fried rice combined with tender beef pieces, eggs, and a medley of fresh vegetables. A hearty and satisfying meal.',
                'ingredients' => 'Basmati Rice, Eggs, Beef, Bell Peppers, Carrots, Spring Onion, Oyster Sauce, Spices',
                'price' => 170.00,
                'discount_price' => null,
                'weight' => '350g',
                'stock' => 25,
                'is_featured' => false,
                'tags' => ['rice', 'beef', 'lunch', 'meal'],
            ],
            [
                'category_id' => $savouryCategory,
                'name' => 'Egg Fried Rice with Prawn',
                'slug' => 'egg-fried-rice-prawn',
                'sku' => 'LVD-EFRP-001',
                'short_description' => 'Premium egg fried rice with fresh succulent prawns.',
                'description' => 'A premium fried rice dish featuring fresh succulent prawns, wok-tossed with eggs and garden-fresh vegetables. A seafood delight that is both satisfying and delicious.',
                'ingredients' => 'Basmati Rice, Eggs, Fresh Prawns, Bell Peppers, Spring Onion, Garlic, Ginger, Soy Sauce',
                'price' => 190.00,
                'discount_price' => 170.00,
                'weight' => '350g',
                'stock' => 20,
                'is_featured' => false,
                'tags' => ['rice', 'prawn', 'seafood', 'premium'],
            ],

            // Sweets
            [
                'category_id' => $sweetsCategory,
                'name' => 'Rosogolla',
                'slug' => 'rosogolla',
                'sku' => 'LVD-RG-001',
                'short_description' => 'Soft, spongy cottage cheese balls soaked in light sugar syrup.',
                'description' => 'Our Rosogollas are made with fresh chenna (cottage cheese), shaped into perfect balls, and cooked to a light, spongy texture in fragrant sugar syrup. A beloved Bengali sweet.',
                'ingredients' => 'Chenna (Cottage Cheese), Sugar Syrup, Cardamom, Rose Water',
                'price' => 15.00,
                'discount_price' => null,
                'weight' => '40g',
                'stock' => 100,
                'is_featured' => true,
                'tags' => ['sweets', 'bengali', 'traditional', 'rosogolla'],
            ],
            [
                'category_id' => $sweetsCategory,
                'name' => 'Gulab Jamun',
                'slug' => 'gulab-jamun',
                'sku' => 'LVD-GJ-001',
                'short_description' => 'Soft milk dough balls soaked in rose-flavored sugar syrup.',
                'description' => 'Deep-fried milk solid dumplings soaked in a fragrant rose and saffron sugar syrup. Our Gulab Jamuns are made fresh daily and melt in your mouth.',
                'ingredients' => 'Khoya, Flour, Ghee, Sugar Syrup, Cardamom, Rose Water, Saffron',
                'price' => 20.00,
                'discount_price' => null,
                'weight' => '50g',
                'stock' => 80,
                'is_featured' => true,
                'tags' => ['sweets', 'traditional', 'gulab jamun', 'syrup'],
            ],

            // Corporate Orders
            [
                'category_id' => $corporateCategory,
                'name' => 'Corporate Snack Box',
                'slug' => 'corporate-snack-box',
                'sku' => 'LVD-CSB-001',
                'short_description' => 'Premium assorted bakery snack box for corporate events and meetings.',
                'description' => 'Our Corporate Snack Box is the perfect solution for office meetings, training sessions, and corporate events. Each box contains a carefully curated selection of our bestselling bakery items including pastries, rolls, sweets, and more. Available in multiple sizes.',
                'ingredients' => 'Assorted Bakery Items (may vary by availability)',
                'price' => 500.00,
                'discount_price' => 450.00,
                'weight' => '1kg (approx)',
                'stock' => 20,
                'is_featured' => true,
                'tags' => ['corporate', 'bulk', 'event', 'office', 'gift'],
            ],
        ];

        foreach ($products as $productData) {
            Product::create($productData);
        }
    }
}
